"""
Analyze Backtest V8
===================
Analyze JSONL datasets generated by V8 historical backtesting scripts.
"""

import argparse
import json
import os
import sys
from typing import Dict, List

import pandas as pd

# Add project root to path
sys.path.append(os.path.join(os.path.dirname(__file__), "..", ".."))

from config import Config


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Analyze Backtesting Results V8 (Limit Entry)")
    parser.add_argument(
        "--file",
        type=str,
        default="data/trading_signals_dataset_v8_iqoption.jsonl",
        help="Path to input JSONL file",
    )
    parser.add_argument("--symbol", type=str, help="Filter by symbol")
    parser.add_argument(
        "--entry_pct",
        type=float,
        default=0.5,
        help="Entry percentage (0.5 = 50%% retracement)",
    )
    parser.add_argument(
        "--safety_margin",
        type=float,
        default=0.1,
        help="Fill margin based on candle range (0.1 = 10%%)",
    )
    return parser.parse_args()


def load_data(file_path: str) -> pd.DataFrame:
    """Load JSONL dataset and flatten nested fields."""
    rows: List[Dict[str, object]] = []

    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Input file not found: {file_path}")

    with open(file_path, "r", encoding="utf-8") as handle:
        for line in handle:
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue

            pattern_candle = entry.get("pattern_candle", {})
            outcome_candle = entry.get("outcome_candle", {})
            signal = entry.get("signal", {})
            technical = entry.get("technical", {})
            metadata = entry.get("metadata", {})

            rows.append(
                {
                    "timestamp": metadata.get("timestamp"),
                    "source": metadata.get("source", "UNKNOWN"),
                    "symbol": metadata.get("symbol"),
                    "pattern": pattern_candle.get("pattern", signal.get("pattern_name")),
                    "direction": signal.get("direction"),
                    "confidence": pattern_candle.get("confidence", signal.get("confidence")),
                    "signal_strength": signal.get("signal_strength", "NONE"),
                    "rsi": technical.get("rsi_value"),
                    "trend_score": technical.get("trend_score"),
                    "pattern_open": pattern_candle.get("open"),
                    "pattern_high": pattern_candle.get("high"),
                    "pattern_low": pattern_candle.get("low"),
                    "pattern_close": pattern_candle.get("close"),
                    "outcome_open": outcome_candle.get("open"),
                    "outcome_high": outcome_candle.get("high"),
                    "outcome_low": outcome_candle.get("low"),
                    "outcome_close": outcome_candle.get("close"),
                }
            )

    if not rows:
        raise ValueError("No valid rows were loaded from the dataset")

    return pd.DataFrame(rows)


def classify_rsi(rsi_value: object) -> str:
    """Map RSI numeric values to zone labels."""
    if pd.isna(rsi_value):
        return "UNKNOWN"

    value = float(rsi_value)
    if value >= Config.RSI_OVERBOUGHT:
        return "OVERBOUGHT"
    if value <= Config.RSI_OVERSOLD:
        return "OVERSOLD"
    return "NEUTRAL"


def calculate_entry_and_result(
    row: pd.Series,
    entry_pct: float = 0.5,
    safety_margin: float = 0.1,
) -> pd.Series:
    """Calculate limit-entry simulation result for one signal row."""
    direction = row["direction"]
    pattern_high = float(row["pattern_high"])
    pattern_low = float(row["pattern_low"])

    outcome_high = float(row["outcome_high"])
    outcome_low = float(row["outcome_low"])
    outcome_close = float(row["outcome_close"])

    signal_range = pattern_high - pattern_low
    entry_price = pattern_low + (signal_range * entry_pct)
    margin_abs = signal_range * safety_margin

    filled = False
    if direction == "PUT" and outcome_high >= (entry_price + margin_abs):
        filled = True
    if direction == "CALL" and outcome_low <= (entry_price - margin_abs):
        filled = True

    if not filled:
        return pd.Series({"entry_price": entry_price, "filled": False, "result": "NO_FILL", "pnl": 0.0})

    if direction == "PUT":
        if outcome_close < entry_price:
            return pd.Series({"entry_price": entry_price, "filled": True, "result": "WIN", "pnl": 0.86})
        if outcome_close > entry_price:
            return pd.Series({"entry_price": entry_price, "filled": True, "result": "LOSS", "pnl": -1.0})
        return pd.Series({"entry_price": entry_price, "filled": True, "result": "ATM", "pnl": 0.0})

    if direction == "CALL":
        if outcome_close > entry_price:
            return pd.Series({"entry_price": entry_price, "filled": True, "result": "WIN", "pnl": 0.86})
        if outcome_close < entry_price:
            return pd.Series({"entry_price": entry_price, "filled": True, "result": "LOSS", "pnl": -1.0})
        return pd.Series({"entry_price": entry_price, "filled": True, "result": "ATM", "pnl": 0.0})

    return pd.Series({"entry_price": entry_price, "filled": False, "result": "INVALID_DIRECTION", "pnl": 0.0})


def print_breakdown(df_grouped: pd.DataFrame, title: str) -> None:
    """Print grouped table with win rate."""
    if df_grouped.empty:
        print(f"\n{title}: No data")
        return

    df_grouped = df_grouped.copy()
    decisive = df_grouped["wins"] + df_grouped["losses"]
    df_grouped["win_rate"] = ((df_grouped["wins"] / decisive) * 100).fillna(0).round(2)
    print(f"\n{title}")
    print(df_grouped.to_string(index=False))


def main() -> None:
    """Entrypoint for V8 backtest analyzer."""
    args = parse_args()

    df = load_data(args.file)
    if args.symbol:
        df = df[df["symbol"] == args.symbol]

    if df.empty:
        print("No rows after symbol filtering.")
        return

    before_filter = len(df)
    df = df[df["signal_strength"] != "NONE"]
    print(f"Filtering NONE signals: {before_filter} -> {len(df)}")

    if df.empty:
        print("No qualified signals available for analysis.")
        return

    required_columns = [
        "pattern_high",
        "pattern_low",
        "outcome_high",
        "outcome_low",
        "outcome_close",
        "direction",
    ]
    for column in required_columns:
        if column not in df.columns:
            raise ValueError(f"Dataset is missing required column: {column}")

    results = df.apply(
        lambda row: calculate_entry_and_result(
            row,
            entry_pct=args.entry_pct,
            safety_margin=args.safety_margin,
        ),
        axis=1,
    )
    df = pd.concat([df, results], axis=1)
    df["rsi_zone"] = df["rsi"].apply(classify_rsi)

    filled = df[df["filled"] == True].copy()

    total_signals = len(df)
    total_filled = len(filled)
    fill_rate = (total_filled / total_signals * 100) if total_signals else 0.0

    wins = int((filled["result"] == "WIN").sum())
    losses = int((filled["result"] == "LOSS").sum())
    atms = int((filled["result"] == "ATM").sum())

    decisive = wins + losses
    win_rate = (wins / decisive * 100) if decisive else 0.0
    total_pnl = float(filled["pnl"].sum()) if not filled.empty else 0.0

    print("\n" + "=" * 60)
    print("BACKTEST RESULTS")
    print("=" * 60)
    print(f"Input file:            {args.file}")
    print(f"Qualified signals:     {total_signals}")
    print(f"Filled trades:         {total_filled} ({fill_rate:.2f}%)")
    print(f"Wins:                  {wins}")
    print(f"Losses:                {losses}")
    print(f"ATM refunds:           {atms}")
    print(f"Win rate (decisive):   {win_rate:.2f}%")
    print(f"Total PnL:             ${total_pnl:.2f}")
    print("=" * 60)

    strength_order = ["VERY_HIGH", "HIGH", "MEDIUM", "LOW", "VERY_LOW", "UNKNOWN"]
    filled["signal_strength"] = pd.Categorical(
        filled["signal_strength"],
        categories=strength_order,
        ordered=True,
    )

    strength_breakdown = (
        filled.groupby(["signal_strength"], observed=True)
        .agg(
            trades=("result", "count"),
            wins=("result", lambda x: (x == "WIN").sum()),
            losses=("result", lambda x: (x == "LOSS").sum()),
            pnl=("pnl", "sum"),
        )
        .reset_index()
        .sort_values(["signal_strength"])
    )
    print_breakdown(strength_breakdown, "BREAKDOWN BY SIGNAL STRENGTH")

    if "trend_score" in filled.columns and filled["trend_score"].notna().any():
        pattern_breakdown = (
            filled.groupby(["pattern", "signal_strength", "trend_score"], observed=True)
            .agg(
                trades=("result", "count"),
                wins=("result", lambda x: (x == "WIN").sum()),
                losses=("result", lambda x: (x == "LOSS").sum()),
                pnl=("pnl", "sum"),
            )
            .reset_index()
            .sort_values(["pattern", "signal_strength", "trend_score"], ascending=[True, True, False])
        )
        print_breakdown(pattern_breakdown, "BREAKDOWN BY PATTERN, STRENGTH, TREND SCORE")
    else:
        pattern_breakdown = (
            filled.groupby(["pattern", "signal_strength"], observed=True)
            .agg(
                trades=("result", "count"),
                wins=("result", lambda x: (x == "WIN").sum()),
                losses=("result", lambda x: (x == "LOSS").sum()),
                pnl=("pnl", "sum"),
            )
            .reset_index()
            .sort_values(["pattern", "signal_strength"], ascending=[True, True])
        )
        print_breakdown(pattern_breakdown, "BREAKDOWN BY PATTERN AND SIGNAL STRENGTH")


if __name__ == "__main__":
    main()
